export enum ProductActionType {
  FETCH_PRODUCT = "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY",
}

export enum CurrencyActionType {
  CHANGE_CURRENT_CURRENCY = "CHANGE_CURRENT_CURRENCY",
  FETCH_CURRENCIES = "FETCH_CURRENCIES",
}
