export enum ProductActionType {
  FETCH_PRODUCT = "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY",
}

export enum CurrencyActionType {
  CHANGE_CURRENT_CURRENCY = "CHANGE_CURRENT_CURRENCY",
  FETCH_CURRENCIES = "FETCH_CURRENCIES",
}

export enum CartActionType {
  ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART",
  INCREMENT_CART_QUANTITY = "INCREMENT_CART_QUANTITY",
  DECREMENT_CART_QUANTITY = "DECREMENT_CART_QUANTITY",
  FETCH_CART_ITEMS = "FETCH_CART_ITEMS",
}
